### ISSUE TITLE
Make a zite favorite/unfavorite from Sidebar

### ISSUE THREAD

**Issue by defder-su** [zeronet-conservancy/zeronet-conservancy#146]
Going to ZeroHello and finding zite looks not such convenient when you already view zite.

**Comment by defder-su** [comment]
I believe it shout be in Sidebar. But don't know where concretely.

**Comment by defder-su** [comment]
Perhaps in Site Control.

**Comment by defder-su** [comment]
I suggest Favorite button after Pause button. The difficulty is translations need revising.

**Comment by caryoscelus** [comment]
done . will make a pr to review soon

**Comment by caryoscelus** [comment]
see #147 for somewhat incomplete implementation

**Comment by caryoscelus** [comment]
closing this now . if anyone wants better implementation , feel free to make a new issue or PR
