### ISSUE TITLE
ValueError: not enough values to unpack in tor manager

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#153]
if tor isn't bootstrapped yet , 0net fails completely

```
in TorManager.py line 54
```

**Comment by atnonesbehest** [comment]
I have a proposal on fixing this though it might be a little unconventional. Please let me know if interested before I put in a pull request

**Comment by caryoscelus** [comment]
update : the issue is not about tor not being loaded , but rather command line parameters being wrong (i was passing only port , but `ip:port` is expected and issue is thrown if it's not that)

@atnonesbehest sure , we're interested ;) feel free to describe or drop a PR and we'll discuss there

**Comment by caryoscelus** [comment]
@atnonesbehest any news ?
