### ISSUE TITLE
AUR package problem

### ISSUE THREAD

**Issue by Pheidologeton** [zeronet-conservancy/zeronet-conservancy#155]
### Step 1: Please describe your environment

  * ZeroNet version: latest git (AUR)
  * Operating system: arch linux
  * Web browser:
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: no. Stock zeronet.conf.

### Step 2: Describe the problem:
Zeronet service does not start
#### Steps to reproduce:

  1. Clone aur repository
  2. makepkg -si
  3. Start zeronet.service

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.
  

  ~~~
  Traceback (most recent call last):
  File "/opt/zeronet/src/main.py", line 58, in <module>
  init_dirs()
  File "/opt/zeronet/src/main.py", line 40, in init_dirs
  os.mkdir(config.data_dir)
  PermissionError: [Errno 13] Permission denied: '/var/lib/zeronet'
  ~~~

#### Expected Results:

  * What did you expect to happen?
Zeronet service works correcly

**Comment by caryoscelus** [comment]
hello and thanks for testing !

please note that i've kept original zeronet PKGBUILD as much as possible

zeronet.install should create zeronet user as /var/lib/zeronet as home directory so it should be writable by zeronet user . can you please show output of `ls -l /var/lib | grep zeronet` ?

also , did you have zeronet previously installed through AUR ?

**Comment by Pheidologeton** [comment]
1) ls -l /var/lib | grep zeronet
empty output
2) Yes, but i delete old zeronet version

**Comment by caryoscelus** [comment]
what about `grep zeronet /etc/passwd` to test if you still have that user present ?

**Comment by Pheidologeton** [comment]
Ouptut: zeronet:x:938:938::/var/lib/zeronet:/bin/bash

**Comment by Pheidologeton** [comment]
Fixed by creating the /var/lib/zeronet folder with zeronet:zeronet permissions
