### ISSUE TITLE
Do not start main zite

### ISSUE THREAD

**Issue by bitcoren** [zeronet-conservancy/zeronet-conservancy#182]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.8
  * Operating system: Windows or Ubuntu 22.04.1
  * Web browser: Firefox
  * Tor status: not available
  * Opened port: no

### Step 2: Describe the problem:

Do not start main zite

#### Steps to reproduce:

git clone https://github.com/zeronet-conservancy/zeronet-conservancy
cd zeronet-conservancy
python3 -m venv venv
source venv/bin/activate
python3 -m pip install -r requirements.txt
python3 zeronet.py

#### Observed Results:

![zeronet](https://user-images.githubusercontent.com/38252897/204161836-4a1b993d-5881-4d79-8772-2f6e3b2e56c9.png)
[debug.log](https://github.com/zeronet-conservancy/zeronet-conservancy/files/10099277/debug.log)

#### Expected Results:

  Start dashboard

**Comment by caryoscelus** [comment]
thanks for reporting ! judging by the log , i've removed what i thought was unused code and this lead to inability to connect to clearnet trackers :/ i've already confirmed that with my node , reverting the change fixes this

sorry for the inconvenience , i suppose i have to release bugfix version now..

**Comment by caryoscelus** [comment]
you can test the changes by switching to `fix_sha1_trackers` branch
