### ISSUE TITLE
ZeroTalks pages refresh for ever

### ISSUE THREAD

**Issue by mahdi-ln** [zeronet-conservancy/zeronet-conservancy#19]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.3 (rev5000) 69aaceb
  * Operating system: EndeavourOS
  * Web browser: _____
  * Tor status: not available
  * Opened port: Not possible by VPN

#### Steps to reproduce:

  1. http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1642926621_1NZftAz9VSawGF5JgMYGFv4ByoKEaQbNZu&amp;amp;amp;amp;wrapper_nonce=ba896576ae2db27d4584b014ddbe24905c5966f9728fd95a19d1e86366e9c96b&amp;amp;amp;wrapper_nonce=f93959e7702a1247c82e4013fc684a7e9478baa49a77ce49c0b2d9ae5bf830e6&amp;amp;wrapper_nonce=88cfe576d930b47c0ed7f6c4571f20e943f31ce4168c10bed9a3e54173dfbdbf&amp;wrapper_nonce=0f021b08638087326d5bff891573ee68f2fdaa982e1b94fabc59e334520252c5

#### Observed Results:

  * Page switch between multiple pages infinitely

**Comment by mahdi-ln** [comment]
Weird it downgraded (!!!) through http://127.0.0.1:43110/1uPDaT3uSyWAPdCv1WkMb5hBQjWSNNACf/ to 0.7.2 (rev4555) and problem solved

**Comment by caryoscelus** [comment]
@mahdi-ln thanks for the report! i should investigate why your initial problem arose, but what's also important is that no upgrading/downgrading should be possible through 0net at this stage. anything that's uploaded on 1update site is not zeronet-conservancy, it's most likely old ZeroNet. i consider upgrading through 0net sites insecure at this point (until proved otherwise) and recommend only updating through git

**Comment by caryoscelus** [comment]
the address you give, though, shouldn't normally arise on zerotalk. removing everything (including) after first `&` should help. can you try reproducing the issue before you get to that malformed url? (i.e. what steps produce it)

**Comment by caryoscelus** [comment]
@mahdi-ln 

i confirmed this happening on firefox for android, but not on desktop firefox . which is pretty weird . can you please try another browser?

**Comment by caryoscelus** [comment]
@mahdi-ln you can test the fix by fetching the `fix_readdress_loop` branch . otherwise it will be merged later today
