### ISSUE TITLE
ZeroNet is not working with NAT and UiPassword on server

### ISSUE THREAD

**Issue by bitcoren** [zeronet-conservancy/zeronet-conservancy#198]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.8.1
  * Operating system: Ubuntu 22.04
  * Web browser: Firefox
  * Tor status: available
  * Opened port: yes with NAT

### Step 2: Describe the problem:

Loop on password page with enter password on external port 5.9.54.142:10402

#### Steps to reproduce:

sudo apt install -y tor
sudo nano /etc/tor/torrc
ControlPort 9051
CookieAuthentication 1
sudo systemctl restart tor
sudo usermod -a -G debian-tor bitcoren

wget -O zeronet.tar.gz https://notabug.org/caryoscelus/zeronet-conservancy/archive/v0.7.8.1.tar.gz
tar -zxf zeronet.tar.gz
mv zeronet-conservancy ZeroNet
cd ZeroNet
sudo apt install pkg-config libffi-dev python3-pip python3-venv python3-dev build-essential
python3 -m venv env
source env/bin/activate
python3 -m pip install -r requirements.txt
mv plugins/disabled-UiPassword plugins/UiPassword
nano zeronet.conf
[global]
fileserver_port = 10401
ui_ip = 10.1.1.104
ui_port = 10402
ui_host =
 5.9.54.142
 10.1.1.104
size_limit = 100
ui_password = password

cd /home/bitcoren/ZeroNet; /usr/bin/bash -c '. env/bin/activate && python3 zeronet.py'

#### Observed Results:

Does not enter to dashboard

[debug.log](https://github.com/zeronet-conservancy/zeronet-conservancy/files/10191305/debug.log)

#### Expected Results:

  Start ZeroNet dashboard

**Comment by caryoscelus** [comment]
thanks for reporting !

i assume it works ok with UiPassword ? do you have cookies enabled ? have you tried accessing UiPassword from localhost ?

**Comment by bitcoren** [comment]
Localhost - Work, 10.1.1.104 - work.
5.9.54.142 - not work, nginx proxy - not work.

**Comment by caryoscelus** [comment]
i remember having some issues experimenting with UiPassword / MultiUser plugins . it was due to some cookie issues , so if you have any , you can try to clear them for those hosts that do not work

**Comment by bitcoren** [comment]
You've already fixed cookie issues in version 0.7.10?

**Comment by caryoscelus** [comment]
not yet

**Comment by caryoscelus** [comment]
btw , i was successfully running some version with nginx reverse proxy

also , did you try that config with any other 0net clients ?

**Comment by bitcoren** [comment]
I'm using ZNX now and it works, I'll check ZNC 0.7.10 with nginx reverse proxy tomorrow.

**Comment by bitcoren** [comment]
sudo nano /etc/nginx/sites-available/default
return 301 https://$host$request_uri;

server {
listen 443 ssl http2;
server_name default_server;
ssl_certificate /etc/letsencrypt/live/chebur.site/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/chebur.site/privkey.pem;
ssl_trusted_certificate /etc/letsencrypt/live/chebur.site/fullchain.pem;
location / {
proxy_pass http://127.0.0.1:43110;
proxy_http_version 1.1;
proxy_read_timeout 600;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
}


Config is not working...

**Comment by caryoscelus** [comment]
did you try removing cookies from failing host ?

**Comment by caryoscelus** [comment]
did you try removing cookies (if any) from failing host ?

**Comment by bitcoren** [comment]
Where is no cookies from chebur.site

**Comment by caryoscelus** [comment]
according to [old docs](https://zeronet.io/docs/faq/#is-it-possible-to-install-zeronet-to-a-remote-machine) , you may want to try --ui_ip "*" and --ui_restrict ip1 ip2

**Comment by bitcoren** [comment]
does not work

**Comment by bitcoren** [comment]
What size donation should we make for you to fix this cookie issues?

**Comment by caryoscelus** [comment]
@bitcoren first i need to be able to reproduce the problem. tried to approximate your config, but it doesn't yield anything interesting. so the easiest way would be if you could give me guest access to your setup. feel free to contact by email, matrix or zeromail
