### ISSUE TITLE
`"max_size" : 0` doesn't seem to work in permissions

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#208]

**Comment by slrslr** [comment]
Maybe this can be closed, because:

parent/global rule override child rule, for example:

```
  "permission_rules": {
   ".*": {
    "files_allowed": null,
    "max_size": 1000
   },
   ".*@08chan": {"max_size": 0},
```

max_size 0 would not work, since it is override by max_size 1000
when parent is 0 too, it start working

**Comment by caryoscelus** [comment]
@slrslr ah yeah , i've noticed this myself , but completely forgot about the open issue . thanks for reminding
