### ISSUE TITLE
zeronet.py siteSign ... is not working to sign user's content.json file

### ISSUE THREAD

**Issue by slrslr** [zeronet-conservancy/zeronet-conservancy#209]
Issue is described here please: https://github.com/ZeroNetX/ZeroNet/issues/212

**Comment by caryoscelus** [comment]
seems to work as intended

> now try to sign and publish that:
> python3 /home/you/zeronet/core/zeronet.py siteSign YourSiteAddress YourSitePrivateKey --inner_path content.json --publish

you need to set inner path to `data/users/userpubkey/content.json` to sign that file

**Comment by slrslr** [comment]
You were right. siteSign is working, yet it does not accept all paths. Apparently accepted paths are:

> --inner_path /data/users/useraddr/content.json
> --inner_path data/users/useraddr/content.json

Though on Linux, I am used to the practice that when utility wants file path, i can enter absolute path or relative path to current directory i am at, but unfortunately Zeronet does not seem to work that way, which is wrong IMO. 

Full path and relative path (`cd zeronet;./zeronet.py siteSign ... --inner_path ./data/siteaddr/data/users/content.json`) cause it to say:

> - Sign error: VerifyError: No rules in main.py line 238 > ContentManager.py line 761 > 876 > 887

Can you please allow user to define absolute/full and relative path to json file?

Beside that, please consider changing "zeronet.py siteSign -h" output from:

>   --inner_path inner_path
>                         File you want to sign (default: content.json)

to something like

>   --inner_path inner_path
>                         File you want to sign. You can not use absolute or relative path, but only input content.json or data/users/content.json ...  (default: content.json)

**Comment by caryoscelus** [comment]
> Can you please allow user to define absolute/full and relative path to json file?

implemented
