### ISSUE TITLE
IP geo-location issue

### ISSUE THREAD

**Issue by d47081** [zeronet-conservancy/zeronet-conservancy#222]
On latest ZNC (master branch) I can't receive geo-location of nodes connected. 
For example, when opening right menu, get following error:

```
GeoLite2 City database download error: check_hostname requires server_hostname!
Please download manually and unpack to data dir:
https://raw.githubusercontent.com/aemr3/GeoLite2-Database/master/GeoLite2-City.mmdb.gz
```

same on stats page
seems that archive link returns 404 and client can't download geo DB on the new ZNC installation

thanks

**Comment by slrslr** [comment]
I can reproduce it.
When i rename zeronet/data/GeoLite2-City.mmdb file, and restart 0.7.10 (rev5120), i also see that error.
[DEBUG log is here](https://bin.disroot.org/?04eb2385b3a324aa#91SbwEUg5KW5bfBrLXbk7HWonC2ed1nkrPDiUpV7Ev9a)

**Comment by caryoscelus** [comment]
i've just left [pr](https://github.com/zeronet-conservancy/zeronet-conservancy/pull/225) for a moment if anyone wants to review . soon to be merged

**Comment by caryoscelus** [comment]
answered in #230

**Comment by parkour86** [comment]
I know this is an old issue, but I was having the same problem. Here's how I fixed it on Ubuntu:

### Option 1: Using a Public Repository
1. Downloaded the tar file from:  
   [https://raw.githubusercontent.com/aemr3/GeoLite2-Database/master/GeoLite2-City.mmdb.gz](https://raw.githubusercontent.com/aemr3/GeoLite2-Database/master/GeoLite2-City.mmdb.gz)  
   Repository: [https://github.com/aemr3/GeoLite2-Database/](https://github.com/aemr3/GeoLite2-Database/)

2. Extracted `GeoLite2-City.mmdb.gz` and moved the file to `/usr/share/GeoIP/`:
   ```bash
   tar -xvzf GeoLite2-City.mmdb.gz
   sudo mv GeoLite2-City.mmdb /usr/share/GeoIP/

3. ZeroNet was then able to copy the file to the appropriate data folder for the zite.

### Option 2: Using MaxMind’s GeoLite2 Free Service

1. Sign up at [MaxMind.com](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data/) and generate a license key for GeoLite2 Free.

2. Download the GeoLite2-City database using your license key:
   ```bash
   wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=YOUR_LICENSE_KEY&suffix=tar.gz" -O GeoLite2-City.tar.gz

3. Extract and move the database:
   ```bash
   tar -xvzf GeoLite2-City.mmdb.gz
   sudo mv GeoLite2-City.mmdb /usr/share/GeoIP/
