### ISSUE TITLE
"original" Zeronet v 0.3.5 replacing tor/.onion with ipv4 (hypothetically)

### ISSUE THREAD

**Issue by wupg98** [zeronet-conservancy/zeronet-conservancy#236]
Hi @caryoscelus !
Thanks for the hint regarding the zne-massive-rework tree being part of zeronet-conservancy.
I made a repository of it.

So my question is not only regarding this tree but also the HelloZeronet/zeronet version 0.3.5(being the initial version containing The onion router and .onion domain name support).
My question starts as follows:
Zeronet v 0.3.5 Rev830 introduced the "Full Tor mode support with hidden services" for the very first time.
My research showed that (atleast back in Rev830 and before the major active forks) these files and directories contained keywords related to TOR or onion:
src/main.py
src/Crypt/CryptRsa.py
src/Config.py 
src/File/FileServer.py
src/Connection/Connection.py
src/Connection/ConnectionServer.py
src/Test/conftest.py
src/Ui/UiWebsocket.py
src/Site/Site.py
plugins/Stats/StatsPlugin.py
plugins/Sidebar/SidebarPlugin.py
src/File/FileRequest.py
src/Peer/Peer.py
src/util/helper.py
plugins/disabled-Bootstrapper/
plugins/AnnounceZero/
plugins/Stats/StatsPlugin.py
tools/tor/
src/Tor
src/Test/TestTor.py
See Changelog:
https://github.com/HelloZeroNet/ZeroNet/compare/v0.3.5...master
keywords (onion,.tor,TorM,tor.,stopTor,downloadTor,file_server.tor,v2,tor_,Tor(,/tor,tor=,torproject,torrc)
So my question now:
What would it hypothetically take to entirely remove the "Full Tor mode support with hidden services"
from lets say ZeroNet v 0.3.5 (or pick any recent version if thats easier to answer) so it entirely used clearnet(ipv4 or even ipv6) instead?

Im asking because it seems a lot of features relevant from the tools, src or plugins folders e.g. BootstrapperDb.py,FileServer.py, Connection.py,Peer.py ,even main.py contain this code. And alot of the were not introduced previously.
And I dont want to break the main peer-to-peer functionality (causing spooky error messages).
With HelloZeronet gone its not really easy to figure it out how to manage a Zeronet client without containing any T.o.R or .onion references.
Im just asking if somebody else ever had this question or wanted to take on this task.
Some of the issue mentioning the background use of T.o.R. Hidden onion services of nofishme /T. Koscis are here:
https://zeronet.io/docs/help_zeronet/network_protocol/
ttps://github.com/HelloZeroNet/ZeroNet/issues/228

If you are interested Im curious to here from youre intel.
BR
wupg98

**Comment by caryoscelus** [comment]
sorry for not answering this sooner

i'm not sure why would you want to do that (if you don't enable tor, it's not going to be used anyway). even if you remove tor functionality from your node code, you'd still be getting potential onion peers that you would need to ignore. other than that, things should keep working if you remove onion-related code branches. unfortunately code isn't structured very well, as you noticed, tor pop ups in many places

but the best solution probably depends on what do you want to achieve by removing tor-related code

**Comment by wupg98** [comment]
Hi good evening! Thanks for youre intel. Just that alot people I know and could be interested to use Zeronet are not so comfortable using the so-called "Tor services" since they only new the negative aspects from news coverage about Darkweb.
From my point of view its not that I just want to make a "fork" that works that way since the "clear net" is alot bigger than the dark one(althought its actually the deep web which is biggest). I keep you posted if I get to make it.

**Comment by wupg98** [comment]
Hi good evening! Thanks for youre intel. Just that alot people I know and could be interested to use Zeronet are not so comfortable using the so-called "Tor services" since they only knew the negative aspects from news coverage about Darkweb.
From my point of view its not that I just want to make a "fork" that works that way since the "clear net" is alot bigger than the dark one(althought its actually the deep web which is biggest). I keep you posted if I get to make it.

**Comment by caryoscelus** [comment]
> not so comfortable using the so-called "Tor services" since they only knew the negative aspects from news coverage about Darkweb.

tor is only used as a transport. but you don't have to tell them about tor at all ;) that said, 0net might have the same "negative aspects"

anyway, i'll be closing this issue since it's not really a code-related issue. feel free to continue discussion if you'd like
