### ISSUE TITLE
Connection to selected interface only

### ISSUE THREAD

**Issue by d47081** [zeronet-conservancy/zeronet-conservancy#240]
I won't to connect ZN using internet, because at least 60% of IPs get blocked  in my country. 
Plus I won't to highlight that connection attempts for ISP.

Is there any way how to allow connection to the `tun0` interface only to prevent data leaks to clearnet?

This question related with #81 but maybe useful for VPN users.

**Comment by caryoscelus** [comment]
not directly, as far as i know. i think using iptables and some form of isolation (e.g. docker or separate user) can be a solution
