### ISSUE TITLE
Unhandled exception: TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb' in <gevent>/greenlet.py

### ISSUE THREAD

**Issue by slrslr** [zeronet-conservancy/zeronet-conservancy#252]
### Step 1: Please describe your environment

  * ZeroNet version: zeronet-conservancy 0.7.10+ r5130
  * Operating system: Debian 11
  * Web browser: Firefox ESR
  * Tor status: available
  * Opened port: yes
  * Special configuration: ____

### Step 2: Describe the problem:

After days of running ZNC, I have found that it is not displaying web page of the http://127.0.0.1:43110/191CazMVNaAcT9Y1zhkxd9ixMBPs59g2um/?Home

Connection with UiServer Websocket was lost. Reconnecting...

dev. console:
```
The connection to ws://127.0.0.1:43110/ZeroNet-Internal/Websocket?wrapper_key=longstringhere was interrupted while the page was loading. [all.js:75:16](http://127.0.0.1:43110/uimedia/all.js?rev=5130&lang=en)
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). [contentScript.js:160:48951](moz-extension://longstringhere/content-script/contentScript.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). [contentscript.js:1:337577](moz-extension://longstringhere/contentscript.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 4 [contentScript.js:160:48951](moz-extension://longstringhere/content-script/contentScript.js)
```

log/debug.log:

`ERROR    - Unhandled exception: TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb' in <gevent>/greenlet.py line 908 > Worker.py line 212 > 189 > 132`

After killing ZN and starting, it seems the issue persist. It did not help to download latest version from git:
git reset --hard;git pull origin master

**Comment by caryoscelus** [comment]
thanks for reporting!

> TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb' in <gevent>/greenlet.py line 908 > Worker.py line 212 > 189 > 132

this part seems to be due to python3.9 having different api for this function (debian 11 most likely implies py3.9, but you can check). i'm going to add compatibility patch

> (moz-extension://longstringhere/content-script/contentScript.js)

while this most likely wouldn't affect the issue, you can try opening the page with extensions disabled (e.g. in private window)

> After killing ZN and starting, it seems the issue persist

what exactly do you get instead of properly loaded page? also, do other pages open normally?

**Comment by slrslr** [comment]
> python3.9 having different api for this function (debian 11 most likely implies py3.9, but you can check).

Yes, Python 3.9.2

> > (moz-extension://longstringhere/content-script/contentScript.js)
> while this most likely wouldn't affect the issue, you can try opening the page with extensions disabled (e.g. in private window)

You were right, all 6 errors and 1 warning not appeared in private Firefox window.

I have no longer seen mentioned "Unhandled exception", so i am going to close this, thank you.
