### ISSUE TITLE
File reading operations on one site never timeout and infinitely blocking loading of all zeronet sites?

### ISSUE THREAD

**Issue by slrslr** [zeronet-conservancy/zeronet-conservancy#259]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.10+ rev8192; python3.9.2
  * Operating system: Linux Debian
  * Web browser: FF

### Step 2: Describe the problem:

When I was loading like 6-8 new, never visited zites (i guess no-peers ones) from ZeroSites / New, then this log line appeared:

> ERROR    - Unhandled exception: OperationalError: database is locked in <gevent>/greenlet.py line 908 > disabled-Bootstrapper/BootstrapperDb.py line 25 > Db.py line 152 > DbCursor.py line 105

But after the connection" expired (failed to download page due to no peers) i think that it freed the connection slot. I am unsure why it connects to a database if the site is new not downloaded. My http://127.0.0.1:43110/Config/ has 10 Database operations threads set.

Later appeared:

> Unhandled exception: Error: Incorrect padding in <gevent>/greenlet.py line 908 > Worker.py line 216 > 162 > BigfilePlugin.py line 404 > ContentManager.py line 998 > 978 > 827 > 802 > CryptBitcoin.py line 91 > libsecp256k1message.py line 135 > <base64> line 87
>
> Db#1:Chart Commit error: OperationalError: cannot commit - no transaction is active in Db.py line 171 (reason: Interval)
>
> Unhandled exception: Error: Incorrect padding in <gevent>/greenlet.py line 908 > Worker.py line 216 > 162 > BigfilePlugin.py line 404 > ContentManager.py line 998 > 978 > 827 > 802 > CryptBitcoin.py line 91 > libsecp256k1message.py line 135 > <base64> line 87

and i am now unable to load any zeronet page (browser shows loading), but it may be different issue to which I have written the details to your Session messenger. Can you please open Session and check it?

**Comment by caryoscelus** [comment]
> But after the connection" expired (failed to download page due to no peers) i think that it freed the connection slot. I am unsure why it connects to a database if the site is new not downloaded

it's a separate bootstrapper (plugin for sharing peers) db, unrelated to site content. i wouldn't expect it to affect site issues, though to be sure you can try to disable bootstrapper plugin altogether
