### ISSUE TITLE
switching main branch to `main`

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#275]
with `main` being new default main branch, it makes sense to switch. current moment seems like a perfect opportunity since there are almost no developers who might be affected by the change. another reason to do this now (i.e. together with the next release) is breaking changes in [data directory structure](https://github.com/zeronet-conservancy/zeronet-conservancy/pull/272), keeping `master` out of that merge will ensure users who do blind pulls will not be affected negatively by it

timeline:
- [x] after #272 / #276 is considered stable, development will happen in `main`
- [x] before the next release `main` becomes official default branch

**Comment by bitcoren** [comment]
When v0.7.11 release?

**Comment by caryoscelus** [comment]
@bitcoren when everything is well tested and welcoming experience is improved; depending on feature development it may turn to be time for v0.8 though
