### ISSUE TITLE
Return [Open site directory] Sidebar feature

### ISSUE THREAD

**Issue by defder-su** [zeronet-conservancy/zeronet-conservancy#30]
**Is your feature request related to a problem? Please describe.**
The legacy HelloZeroNet has a feature [Open site directory] in Sidebar. It has been removed when [added [Browse files] feature](https://github.com/zeronet-conservancy/zeronet-conservancy/commit/52ed8c18ca0f009e3fe327fe35fc9995b044d70c). But that was convenient to open directory in system file manager.

**Describe the solution you'd like**
Return `<a href='#Site+directory' id='link-directory' class='link-right'>{_[Open site directory]}</a>` line before `<a href='/ZeroNet-Internal/Zip?address={site.address}' id='link-zip' class='link-right' download='site.zip'>{_[Save as .zip]}</a>` in `plugins/Sidebar/SidebarPlugin.py`.

**Comment by caryoscelus** [comment]
hey there , that sounds reasonable ^_^ i'll get to it when i'm done with some other coding .. or feel free to make that a pull request ;)
