### ISSUE TITLE
make zero:// links work

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#31]
it's more complicated than i thought due to iframe issues , but it would help both with transitioning & proxies

**Comment by Robotizing** [comment]
`zero://` scheme is already used by zeronet trackers. Is it possible to use it also to browse zites?

Also, many browsers consider URL hostnames as [case-insensitive](https://blog.mauve.moe/posts/protocol-comparisons#links-ipfs).

**Comment by caryoscelus** [comment]
the idea was to do something like link-rewriting in js, but as other new features it's not actively planned to be implemented

the reason is that links with hostname aren't going to work for people with non-default setup (including proxies) and hostname-less links (such as `/1MCoA8rQHhwu4LY2t2aabqcGSRqrL8uf2X/`) are not made into hyperlinks by default markdown nor do they look meaningful outside of 0net

**Comment by caryoscelus** [comment]
this is both not reasonably possible on 0net level and also related to soon-to-become-deprecated site schema so closing
