### ISSUE TITLE
Config not saving

### ISSUE THREAD

**Issue by vartiovaara** [zeronet-conservancy/zeronet-conservancy#33]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.3.2 r5002, commit 072a5dd
  * Operating system: Manjaro Linux
  * Web browser: Firefox Nightly 99.0a1 (2022-02-09)(64-bit) and Brave (Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) unknown (64-bit))
  * Tor status: disabled
  * Opened port: no
  * Special configuration: Installed per instructions in readme.

### Step 2: Describe the problem:
When trying to update settings, the configuration change button starts an never-ending "loading animation".
This lasts until site is reloaded, and no settings were changed.

#### Steps to reproduce:

  1. Install zeronet-conservancy per instructions.
  2. Go to http://127.0.0.1:43110/Config
  3. Try to change any of the settings (for example port number and logging level)
  4. Observe behaviour as explained.

#### Observed Results:

![image](https://user-images.githubusercontent.com/64323553/155784084-bb7d0a4f-e686-4a51-9e07-36da378563eb.png)
This lasts indefinately until site reload.

#### Expected Results:

 I expected the settings to save.

**Comment by caryoscelus** [comment]
thanks for report ! i think i've seen something like that a bit ago and the config was actually being saved (you can test if that's the case by looking at zeronet.conf or reloading the page) , just the page issue . i'll try to get to this asap , but i don't have much time resources

**Comment by caryoscelus** [comment]
closing this for now as without further details we cannot help sort this out . feel free to reopen with more info
