### ISSUE TITLE
make id certificate checking optional

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#36]
originally posted on ZeroTalk: http://127.0.0.1:43110/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/?Topic:1648583593_13oRBYqNeUr6Tvgt4KkAT9FT4XRiKFBjnE/obsoleting+ZeroID+looking+for+consensus

so more and more users who try to join 0net discover that they can't obtain ZeroID anymore. there are a few things we can do about this: ask people to add different id providers on their sites (wouldn't work: not every actively used site is maintained), fake ZeroID or get rid of the "certificate" idea altogether.

i think we should do the latter option. certificates other than ZeroID were never meaningful: they either don't fulfil intended task (ensuring unique names and potentially validating identities) by allowing any ID to be used any number of times or haven't lived for any serious period of time. and ZeroID that at least provides unique names was never good: it was a centralized server created to emulate clearnet feel of [usernames@domains](mailto:usernames@domains). it was a crutch. we should just disable cert checking and use cryptographic IDs (at least for everyone who doesn't have an existing ID).

there are two issues with this:

- outdated nodes will not see or propagate data by users w/o certificates

- generating ids becomes 0 cost so spam attacks are more viable

first issue requires certain amount of people signing off with this. we don't need everyone's agreement, just an active majority.

second issue might be fixed by introducing alternative system. no one is going to write it though. so we have a choice of facing spam or death of the network. on the bright note, we're still to see spam attacks on kaffie hub or any other site accepting kaffie (or other similar) ids. regardless, this is short-term question. 0net is not going to last forever and its best chance is to get integrated into a better network

**Comment by d4708** [comment]
As you actively contribute to the project, have experience, and new ideas - it is the nice time to create independent, branded fork with it own specifics and users, who following this project.

I don't like 0net official pathway, and agreed with think that the main priority in the less features and more safety for users.
Also I vote to have just optional namecoin relations, and generate new profiles instantly on the node installation, based on the private/public keys just, to sign the profile data.

P.S. some documentation - pretty important moment, because it is hard to understand 0net basics and difference between the current project, I think, it would be human-friendly website, not readme.md just on github..

**Comment by caryoscelus** [comment]
my priority is new network and i'm trying to keep 0net (and conservancy in particular) only to the point where migration would be possible (original reason for this fork was to give people option use minimally patched latest official with tor-v3 enabled, instead of jumping on a dubious self-proclaimed continuation of zn)

with my time being even more limited than before, i can't afford to spend much of it on this, ultimately legacy, codebase. this proposal, that would largely solve one of the biggest new-user-facing issues, was largely ignored and there's little sense in implementing it without people willing to upgrade

> 0net official pathway

just a reminder that official [zn](https://github.com/HelloZeroNet/ZeroNet) is dead at this point ;)

> P.S. some documentation - pretty important moment, because it is hard to understand 0net basics and difference between the current project, I think, it would be human-friendly website, not readme.md just on github..

this is true, but then again, i don't want to waste time by documenting something that i want to deprecate asap

**Comment by d4708** [comment]
Thank for reply, have answered just with related post here:
https://github.com/zeronet-conservancy/zeronet-conservancy/issues/34#issuecomment-1114592617

**Comment by d4708** [comment]
Nice news!

How can I test:

```
git pull
git checkout nocert
source venv/bin/activate
python3 zeronet.py
```
If these steps are correct - it's no changes. The sign in button still required for replies (I'm already registered).
Maybe need to clear some profile folder?

![2022-05-12_14-27](https://user-images.githubusercontent.com/96319366/168064755-c1721bbb-4e96-420d-991c-8299c5f0f52a.png)

Sorry I'm not familiar with 0net, this feature/branch is no login required anymore?

**Comment by caryoscelus** [comment]
> Sorry I'm not familiar with 0net, this feature/branch is no login required anymore?

not quite there yet . to test out :

- you still need to "register" on kaffie id (chosen arbitrarily among many pseudo-certificate centers) if you don't have acc there yet
- then if you click on "sign in as" on e.g. zerotalk , you'll see that your kaffie-id is greyed-out (i.e. unable to be used) , as before (this will be also fixed later)
- so in order to use kaffie id , you need to open sidebar (drag the "0" button in the top-right corner to the left) , scroll down to "IDENTITY ADDRESS" and click on "change" - then it'll allow you to choose your kaffie-id and you'll be able to post
- note that these posts will only propagate to a few nodes that support this change so you're likely to get "content publish failed" , but if you get to that stage it means that your node already considers this content valid

**Comment by d4708** [comment]
mm, looks pretty hard for me yet..

what about auto-generating private/public keys on the first startup, where public key - is the username (that could be aliased with third-party name-servers, if needed).

or I have said something stupid?

just in my vision, this conception creates the profile instantly, without any the acts. Also, existing user can be imported trough private key (seed) providing.

for human-readable reasons, the hash could be visualized using procedural avatar generation - it's easy to remember specified user by picture (like we are remembering faces). and interact with this user trough UI interface buttons, links, etc without keep that in memory.

look at here - I found this conception pretty workable and useful (at least for myself)
https://kvazar.today/NYWVd5zjSjgZLdoKSSf4Si9C7oWQMxtJky

p.s. imho, human-readable usernames - are not unique, has no sense around the web. the public key hash, looks like so)

**Comment by caryoscelus** [comment]
i pretty much agree with what you say . however providing backward compatibility with zerotalk and any other site requires either patching their js code (which is a big hassle) or giving them something that looks like a valid certificate , even if that is exactly auto-generated keys

all of this is temporary solutions , the plan is to eventually migrate all the data and keep the system clean of such hacks . however , in order to get there without losing users , i'm inventing ways of introducing gradual changes which can be quickly adopted and supported by the community

**Comment by d4708** [comment]
By integrating my first 0net website (described in #45) finally I've understand how does network work. By the fact, everything is the website, signed by private key, even zero's main page. Web interface just implements author's features like zero ID's - it is just consensus inside the network. And all these features like blogs, mailing, etc simply included to the initial web UI package.

So, I think - that's super cool, because we can definitively rewrite the client-side without zero ID relations, or make it optional.

How is the content researching implemented? Suppose it is external requests to some back-end crawler that interacts trough API or maybe trackers. How these crawlers indexing content?

**Comment by caryoscelus** [comment]
> By integrating my first 0net website (described in https://github.com/zeronet-conservancy/zeronet-conservancy/issues/45) finally I've understand how does network work. By the fact, everything is the website, signed by private key, even zero's main page. Web interface just implements author's features like zero ID's - it is just consensus inside the network. And all these features like blogs, mailing, etc simply included to the initial web UI package.

basically yes . but there's also a whole sqlite thing attached to make dynamic sites more dynamic ... 

> So, I think - that's super cool, because we can definitively rewrite the client-side without zero ID relations, or make it optional.

yes , but as you've observed with your site it's not very comfortable to make new client-side sites . on the other hand , it'd be nice to keep old sites running , while allowing to e.g. add comments to them w/o zeroid

eventually i want to make different , effective and convenient api , but more focused on simply allowing people to reach consensus on who's allowed to do what on sites instead of relying on site owners handling that fairly

> How is the content researching implemented? Suppose it is external requests to some back-end crawler that interacts trough API or maybe trackers. How these crawlers indexing content?

once you download a site/its potential update , 0net client looks for `content.json` file , verifying signatures and rules and decides which files to download , whether they are valid or not etc . there's no cross-site crawling . i'm pretty sure site updates are handled via trackers and already established peer connections

**Comment by caryoscelus** [comment]
this will probably not be implemented as previously intended because overriding certificate mechanism while keeping `content.json/dbschema.json` style seems like a waste of effort
