### ISSUE TITLE
Rewriting the application from Python to Rust

### ISSUE THREAD

**Issue by patranger** [zeronet-conservancy/zeronet-conservancy#37]
**Is your feature request related to a problem? Please describe.**
 While using the application, I noticed that it was running very slowly. Problems installing Python dependencies.

**Describe the solution you'd like**
 Rewriting the application from slow Python to Rust would speed up the application a lot.

**Comment by caryoscelus** [comment]
i'm closing this issue as the project will not be rewritten in rust . `riza` will be written from scratch in a different lang .

please feee free to open specific issues about dependencies and performance issues
