### ISSUE TITLE
How to import existing account?

### ISSUE THREAD

**Issue by d4708** [zeronet-conservancy/zeronet-conservancy#44]
I had registered username trough zero.bit service and then, installed new node with other certificates at the data folder.

How can I properly import my existing seed key as don't see any the UI tools for that, just creating new one?
I won't to import all folder, maybe few rows in config changing would be enough?

Thanks!

**Comment by d4708** [comment]
Just copied all my data folder. I want to backup account, and network cache takes a lot of space for these needs.

**Comment by caryoscelus** [comment]
all you need is `users.json` and `sites.json` (and `filters.json` if you have them setup) – basically all `.json` filters from root `data/` directory . everything else , if you're not the only seeder , is on the network and can be synced back

**Comment by caryoscelus** [comment]
see #49 for future solution proposal

**Comment by d4708** [comment]
thank you, I have saved `users.json` and `sites.json`

suppose, the subject could be closed.
