### ISSUE TITLE
Requirements installation error

### ISSUE THREAD

**Issue by ghost** [zeronet-conservancy/zeronet-conservancy#46]
I had some errors on installation 0net on the one of my machines running latest Debian. Unfortunately lost raw log, just bellow.
In my case, few additional packages needed to be installed manually - it solve the issue. Maybe should be added to README or requirements file?

`python3 -m pip install -U idna`

and

`apt install pkg-config`

Just for a note.

**Comment by caryoscelus** [comment]
`pkg-config` sounds like a legit dependency , feel free to make a pull request adding that to README

idna sounds harmless to me , but i don't understand why should it be there and would like to investigate more (i've had nodes running on debian , android/termux and mac os , none required manually installing idna)

thanks for reporting !

**Comment by d4708** [comment]
I don't know too, so asking because creating pull request, suppose it is just some OS builds specifics, that not including this software by default.

One think - I forgot to create separated branch for my contribution before creating the pull request.

**Comment by caryoscelus** [comment]
seems to be resolved , so closing . feel free to reopen if the issue persists
