### ISSUE TITLE
New project logo

### ISSUE THREAD

**Issue by ghost** [zeronet-conservancy/zeronet-conservancy#50]
Yesterday, I had played with favicon for one of my project, finally get an idea, that would be more compatible for zeronet one :)

Also, prefer some plain templates, with minimum dynamics and special effects blinking, maybe the subject for new template also. Just thoughts would be nice to make some rebranding as this project looks pretty interesting.

![logo](https://github.com/kvazar-network/webapp/raw/3b0ad190b5212a3d4639d97fe8c7574a9e68da2e/public/image/favicon-light.png)

**Comment by caryoscelus** [comment]
for now i've adopted mix of riza logo , original 0net logo and `convservancy` label as you can see @ https://github.com/zeronet-conservancy . haven't seen it in favicon size though %_% so using something simpler might be better

but i also have to consult with my designer division ;)

**Comment by d4708** [comment]
you have nice art choices in your sites!

**Comment by caryoscelus** [comment]
thx! i've dabbled in game art making , as well as dropping out from art school back when i was a kid ;)

**Comment by caryoscelus** [comment]
not sure the new icon is perfect as favicon , but i've updated it , so feel free to test and give feedback (currently both in `master` and `dev` , `nocert` branch is WIP atm)

**Comment by d4708** [comment]
I like it because unique project sign by it author. Also it includes the previous little one, as the parental relation.

Just need to be nicely visible for 16x16 sizes in details, and maybe xcf beside psd..

> currently both in master and dev , nocert branch is WIP atm

Seems it is just graphics update - I did not see the commits related with code changing. Maybe I don't know what is 'WIP atm'

**Comment by caryoscelus** [comment]
> Just need to be nicely visible for 16x16 sizes in details, and maybe xcf beside psd..

i'm making things in Krita , but yeah could post sources , good idea

> Seems it is just graphics update - I did not see the commits related with code changing. Maybe I don't know what is 'WIP atm'

my local `nocert` is slightly ahead of published one and is more broken/less useful for testing , so i don't want to push it until that phase is over basically
