### ISSUE TITLE
Apple Touch Icon

### ISSUE THREAD

**Issue by d4708** [zeronet-conservancy/zeronet-conservancy#63]
:43110/apple-touch-icon.png

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
```

```
<style>
* { font-family: Consolas, Monospace; color: #333; }
code { font-family: Consolas, Monospace; background-color: #EEE }
</style>
<h1>Not Found</h1>
<h2>src/Ui/media/img//apple-touch-icon.png</h3>
```

**Comment by d4708** [comment]
Let me fix - I know a nice service for these needs
https://realfavicongenerator.net

**Comment by caryoscelus** [comment]
what is it used for , though ?

**Comment by d4708** [comment]
I just attach the icons set here, because not sure also about SVG one #50

p.s. I have an issue that favicon not updating in my FF new tab favs. 
p.p.s. Maybe 3px tab icon would be better also, really not sure for right now what of this set we are really needed.

[favicon_package_v0.16.zip](https://github.com/zeronet-conservancy/zeronet-conservancy/files/8729237/favicon_package_v0.16.zip)

**Comment by d4708** [comment]
Just for a note: some relations exists on the server-side

_plugins/disabled-UiPassword/UiPasswordPlugin.py_
_src/Ui/UiRequest.py_

Seems constructions are needed to pass `Per-site favicon` described in _CHANGELOG.md_
