### ISSUE TITLE
can't handle simple curl request without exception

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#67]
```
$ curl  127.0.0.1:43110

                <style>
                * { font-family: Consolas, Monospace; color: #333; }
                code { font-family: Consolas, Monospace; background-color: #EEE }
                </style>
                <h1>Server error</h1>
                <h2>UiWSGIHandler error: TypeError: object of type &#x27;generator&#x27; has no len()</h3>
^C
```

**Comment by d4708** [comment]
Nice catch for tests, according to stackoverflow, this error mostly cause to the deprecated interpretation constructions, my experience in Python read-only, just trying to understand how to fix that too. This error also in #43

**Comment by caryoscelus** [comment]
> it works for me, that is GET request?

what does it output for you , though ?

**Comment by d4708** [comment]
in my case it returns login page (because of plugin) suppose it returns default wrapper.

seems it is your local issue

**Comment by caryoscelus** [comment]
more like plugin is masking the issue for you ;) it was initially reported by another person and i already encountered it before on completely other setup

**Comment by caryoscelus** [comment]
`curl -H "Accept: text/html" localhost:43110/Stats` can be used as a workaround for now
