### ISSUE TITLE
make sure docker works / write docker setup instruction

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#70]

**Comment by caryoscelus** [comment]
@FraYoshi have you tackled this yet?

**Comment by FraYoshi** [comment]
Not yet, might work on it late next week! >.<
Unless prtngn already have started working on it

**Comment by caryoscelus** [comment]
docker is back , @prtngn is still working on improving it (so i'm not closing yet) and then we'll get to documenting it

**Comment by caryoscelus** [comment]
@FraYoshi feel free to test how new docker works for you ;)

**Comment by FraYoshi** [comment]
it works for me! (Arch, Linux) 🙌
dropping the command in case others want to try it 😉

`docker run --rm -it -v /<path/to/0n/data/directory>:/app/data -p 43110:43110 -p 26552:26552 zeronet-conservancy`

**Comment by prtngn** [comment]
I't good news ) Later we add docker-compose.yml with 0net and tor containers.
